### ISSUE TITLE
Replica Sets Not Working

### ISSUE THREAD

**Issue by niftylettuce** [winstonjs/winston-mongodb#39]
I currently have a `dbUri` specified in my `options` object, however it appears this code in `lib/winston-mongodb.js` is only allowing me to use the one host (as `replicaSet` is not parsed by `muri` package)?

```js
    } else if (uriOptions.hosts && uriOptions.hosts[0]) {
      options.host = uriOptions.hosts[0].host;
      options.port = uriOptions.hosts[0].port;
    }
```

Therefore when using `dbUri`, no writes to the DB are working with this package.

**Comment by pwielgolaski** [comment]
I played a bit with replicateset setup and it seems that current implementation is not handling properly reconnects (it works ok for single server, but not for replica set), it seems to be feature/bug in mongodb implementation. It is working fine when I use keepAlive=true in options. 
Could we switch to using MongoClient.connect instead or open? 
Is there any particular reason why mongodb is in 1.4 version rather than 2.0?

**Comment by 39dotyt** [comment]
Fixed in https://github.com/winstonjs/winston-mongodb/commit/bf8a1c0925b3bcbf923b81cd62a37b42cfe6eac5.

**Comment by niftylettuce** [comment]
Thanks
